# This is a basic workflow that is manually triggered

name: Ram workflow random


on:
   workflow_dispatch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: run hub commands
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         curl \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
         https://api.github.com/repos/Ramudu-stockone/Action_test/branches |\
         python3 -c "import sys, json; for i in json.load(sys.stdin):   print(i['name'])"
