# This is a basic workflow that is manually triggered

name: Ram workflow random

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: run hub commands
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |  
          hub pull-request   -b release1   -h main -m "request came from workflow" -l "feature, automated pr" || true
          hub pull-request   -b release2   -h maim -m "request came from workflow" -l "feature, automated pr" || true
          
