# This is a basic workflow that is manually triggered

name: Ram workflow random

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: run hub commands
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |  
          hub pull-request   -b ${GITHUB_REF##*/}  -h main -m "request came from workflow" -l "feature, automated pr" || true
          
